<?php
/*
1000x original
--------------
Short           0.03s
Short with tags 0.29s
Simple          0.03s
With tags       1.56s

100x new
--------
Short           1.02s
Short with tags 1.24s
Simple          44.41s
With tags       47.42s
*/

include __DIR__ . '/vendor/autoload.php';

$textShort = <<<EOS
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec augue risus. In eu nisl quis augue hendrerit aliquet. Sed tempor metus ac dolor elementum, et volutpat ex vestibulum. Aenean in laoreet mauris. Aenean sagittis libero magna, nec consequat nisi pretium aliquam. Pellentesque egestas est id orci tempus, a vehicula elit cursus. Mauris faucibus commodo quam, quis volutpat diam viverra eget. In hac habitasse platea dictumst. Sed eleifend pellentesque velit, vitae elementum sapien dignissim nec. Nunc rhoncus malesuada odio, vel blandit magna finibus quis. Vestibulum quis mauris lacus. Mauris a malesuada urna.
EOS;

$textShortWithTags = <<<EOS
<comment>Lorem ipsum dolor sit amet</comment>, <fg=red;bg=white;options=bold>consectetur</> adipiscing elit. <info>In nec augue risus. In eu nisl quis augue hendrerit aliquet</info>. <error>Sed tempor metus</error> ac dolor elementum, et volutpat ex vestibulum. Aenean in laoreet mauris. Aenean sagittis libero magna, nec consequat nisi pretium aliquam. Pellentesque egestas est id orci tempus, a vehicula elit cursus. Mauris faucibus commodo quam, quis volutpat diam viverra eget. In hac habitasse platea dictumst. Sed eleifend pellentesque velit, vitae elementum sapien dignissim nec. Nunc rhoncus malesuada odio, vel blandit magna finibus quis. Vestibulum quis mauris lacus. \<visible>Mauris\</visible> a malesuada urna.
EOS;


// Generated 50 paragraphs, 4301 words, 29253 bytes of Lorem Ipsum
$textSimple = <<<EOS
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec augue risus. In eu nisl quis augue hendrerit aliquet. Sed tempor metus ac dolor elementum, et volutpat ex vestibulum. Aenean in laoreet mauris. Aenean sagittis libero magna, nec consequat nisi pretium aliquam. Pellentesque egestas est id orci tempus, a vehicula elit cursus. Mauris faucibus commodo quam, quis volutpat diam viverra eget. In hac habitasse platea dictumst. Sed eleifend pellentesque velit, vitae elementum sapien dignissim nec. Nunc rhoncus malesuada odio, vel blandit magna finibus quis. Vestibulum quis mauris lacus. Mauris a malesuada urna.

Cras sed hendrerit mauris, et condimentum arcu. Vestibulum dictum condimentum ex, sit amet ornare felis placerat et. Nunc dictum convallis massa, vitae efficitur erat varius a. Maecenas venenatis sollicitudin vehicula. Vivamus placerat neque tortor, ullamcorper egestas neque pharetra vel. Quisque molestie malesuada semper. Suspendisse pharetra sem nec dui pharetra vehicula. Proin id pharetra justo, a tempor sapien. Quisque finibus luctus commodo. Nam ligula orci, dictum sit amet auctor sed, tristique nec nisi. Proin faucibus sollicitudin velit, id dictum diam. Donec mollis, nibh sed consequat euismod, ligula elit tempus leo, sed tincidunt mauris tortor consectetur dui. Proin consequat dolor in sagittis posuere. Mauris facilisis felis quam, quis iaculis ligula lacinia vel. Suspendisse a est scelerisque nulla ultrices condimentum quis ut lectus. Etiam id tellus turpis.

Cras augue tellus, molestie sit amet orci id, maximus congue massa. Nam sagittis nisi tortor, vel tempus orci luctus sit amet. Maecenas nunc est, dignissim eu lacus ut, accumsan commodo tortor. Morbi congue malesuada sem, vel faucibus arcu maximus a. Praesent tincidunt ex at ultrices egestas. Nunc nunc tortor, laoreet in eros consequat, hendrerit fringilla mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tincidunt, enim a feugiat vulputate, mi libero convallis velit, ut feugiat risus lectus sit amet ex. Sed porttitor rutrum augue eget vestibulum. Nam ultrices sem vehicula justo pharetra consectetur sed id enim. In tempor pharetra ante id tincidunt.

Aenean tempor euismod quam, nec venenatis nulla. Etiam vitae nisl volutpat, faucibus neque eget, ornare dolor. Ut sapien nisl, vulputate non urna eget, lacinia dictum ante. Pellentesque quis nunc hendrerit, tincidunt dolor vel, lobortis eros. Aenean volutpat ligula velit, varius commodo diam consequat ac. Suspendisse efficitur facilisis condimentum. Maecenas fermentum egestas lacus, in varius dui faucibus et. Proin nec turpis ut quam volutpat auctor id eu libero. Suspendisse potenti. Proin quis velit vel dui dictum mattis. Aliquam erat volutpat. Donec convallis ante a nunc tristique vestibulum. Aliquam at molestie nulla, vel porttitor urna. Duis hendrerit, lacus ut dapibus fermentum, dolor massa gravida nulla, sit amet convallis leo mi vel nisl. Curabitur elementum elementum vehicula.

Quisque egestas nunc eget posuere mattis. Fusce eget neque consectetur, sollicitudin ex nec, vulputate felis. Vestibulum purus dolor, pretium vel tempus sed, euismod non dolor. Vivamus ultrices rhoncus risus non scelerisque. Phasellus leo augue, bibendum eget justo vitae, elementum sagittis leo. Curabitur velit magna, congue sit amet mi eu, luctus mattis augue. Morbi vel metus magna. Mauris porta augue dolor, a fringilla mauris interdum vel. In ac suscipit ligula, non ornare mauris. Aenean id venenatis ligula, vel dignissim leo. Donec tortor leo, fringilla in massa sit amet, varius pulvinar nulla. Proin luctus a felis ut dictum.

Duis ut malesuada enim. Sed felis nisl, porttitor eu lacus eu, ornare vestibulum sapien. Proin pharetra dui quis neque finibus ultricies. Vestibulum id aliquam lacus, id lacinia metus. Duis eget turpis ac neque sollicitudin imperdiet. Maecenas dolor tellus, bibendum ac ligula ac, vehicula consequat ante. Pellentesque turpis elit, tincidunt id semper sit amet, rutrum nec dui. In eget nulla quis sapien pulvinar bibendum eu sit amet nunc. Aliquam vel ullamcorper dui. Cras nec dolor sit amet dolor euismod aliquet.

Morbi id mauris turpis. Etiam faucibus euismod neque nec pretium. Duis vitae nisi volutpat, porttitor est a, condimentum metus. Nam viverra iaculis ligula sit amet blandit. Morbi quis sem tristique, convallis justo in, ultrices nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque condimentum cursus molestie. Maecenas condimentum dapibus velit sit amet pretium. Integer a arcu et diam pretium dignissim nec id tellus. Ut nec elementum nibh, sit amet finibus ligula.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean leo augue, tempor nec finibus pharetra, tincidunt id libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pellentesque vitae dolor a rutrum. Sed congue consectetur sapien. Vivamus quis varius orci. Proin eget consequat dolor. Proin eu sagittis ex, quis porta est. Proin varius iaculis justo. Aliquam et lacus et nulla sollicitudin laoreet in at sem. Sed velit est, lacinia id risus sit amet, convallis finibus ante. Quisque ut turpis quis nunc facilisis sodales. Aenean viverra tortor sed feugiat tristique. Sed lectus arcu, imperdiet quis sodales sed, lobortis id ligula. Praesent aliquet eleifend placerat. Ut in magna pulvinar, rutrum sem vehicula, interdum leo.

Phasellus id ipsum quis sem lobortis ullamcorper. Quisque laoreet erat turpis, ut aliquam magna ornare id. Nullam id leo eu mi suscipit tincidunt. In consectetur ac sapien vitae facilisis. Aenean viverra nibh in purus mattis, sed tincidunt purus lobortis. Mauris eget erat mattis, rhoncus neque et, tincidunt lacus. Donec sed luctus purus.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam efficitur vitae felis eget molestie. Donec erat odio, rutrum id ornare vel, accumsan vel tellus. Suspendisse eros velit, ornare blandit turpis at, imperdiet sollicitudin dui. Maecenas interdum, est a scelerisque semper, diam augue fermentum mi, at tincidunt odio leo in nibh. Nulla interdum eros ac euismod egestas. Nam in magna dapibus, ultricies nibh at, sagittis leo. Vestibulum nec egestas velit.

Nullam eleifend leo sapien, vel aliquet dolor rutrum ut. Maecenas consectetur elit nec massa placerat, in cursus mi varius. Sed sed ante ut nisl tincidunt elementum. Sed dictum nisl eget nibh imperdiet cursus. Praesent posuere convallis convallis. Nulla nec massa quis diam dictum convallis. Morbi non diam nisi. Pellentesque elit nisl, tincidunt in mi ac, mollis vehicula risus. In cursus ligula ut dolor mollis congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus at enim sed felis fringilla efficitur.

Praesent lacus magna, rutrum malesuada dapibus in, gravida a risus. Suspendisse euismod diam velit, at condimentum magna volutpat nec. Duis tempor ut sem a egestas. Etiam volutpat sem ultricies congue pharetra. Maecenas vitae nisi et lectus pulvinar lacinia ac a velit. Integer at mi eget leo dignissim porta. Phasellus luctus enim vel sem interdum consectetur. Nunc interdum, magna nec commodo tempor, diam ex sollicitudin mi, vitae tempus tortor sem id purus. Pellentesque semper mattis eros, et sollicitudin orci pellentesque sed. Nunc aliquet leo sit amet varius iaculis. Phasellus eget libero convallis, lobortis ligula in, rutrum lectus. Aliquam erat volutpat. Cras in tristique enim.

Vivamus fermentum vestibulum tempor. Maecenas mollis id risus at rutrum. Quisque sodales eget metus blandit viverra. In quis consectetur orci. Proin viverra placerat consequat. Aenean arcu justo, ultrices nec semper id, feugiat a orci. Aenean posuere nisl malesuada magna sollicitudin, ultricies luctus eros vehicula. Vestibulum bibendum et purus fringilla vulputate.

Suspendisse sollicitudin molestie congue. Etiam tristique suscipit risus, vel tristique mauris cursus vitae. Phasellus semper urna quis orci ultrices finibus. Aliquam convallis risus placerat nisi laoreet, eu scelerisque enim maximus. Duis eleifend in augue quis laoreet. Ut ligula justo, fermentum id dolor vitae, facilisis congue augue. Nunc ac ultricies dui, quis pharetra purus. Nullam auctor consequat mollis. In velit velit, tincidunt id mi ut, molestie accumsan erat.

Donec luctus sem vel sapien dignissim ultricies. Etiam quis enim nulla. Curabitur consequat elit in dui placerat, sed euismod sem mattis. Fusce ultricies posuere tellus, a facilisis elit rutrum bibendum. Donec consequat feugiat orci ac blandit. Quisque ac neque nisi. Pellentesque placerat volutpat mauris, et accumsan ex dignissim at. Cras sagittis, mi nec malesuada dignissim, lectus enim ultricies justo, vitae venenatis felis velit in quam. Suspendisse potenti.

Donec elementum, risus in auctor euismod, purus sapien pellentesque lacus, ut sollicitudin erat purus quis urna. Maecenas non massa tincidunt, ullamcorper turpis vitae, egestas nulla. Fusce sit amet risus pharetra, efficitur augue ac, dictum elit. Sed eget sapien erat. Ut tempus bibendum varius. In elementum, ipsum et viverra malesuada, ligula ex convallis eros, ac facilisis arcu lectus eu justo. Curabitur venenatis consequat massa, ut dictum nisl posuere vitae.

Aenean pellentesque velit non molestie auctor. Vestibulum ut velit turpis. Sed vitae nisl maximus leo vestibulum bibendum eu sed arcu. Suspendisse mollis nibh non tellus pretium, eu accumsan mauris aliquam. Suspendisse vitae magna finibus, dictum orci at, eleifend purus. Mauris viverra sollicitudin quam id tincidunt. Quisque condimentum ac mi vel aliquam.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis sodales tortor urna, et volutpat magna aliquet in. Proin aliquet iaculis dolor, ac lacinia purus faucibus eu. Curabitur at tincidunt sapien. Donec ullamcorper hendrerit neque, in condimentum velit suscipit a. Donec viverra dui sit amet leo sodales, vel rutrum nunc elementum. Mauris eget massa molestie, placerat leo in, varius lectus.

In a mi eu ex finibus dictum. Sed viverra consectetur velit. Curabitur consectetur tortor nec egestas tincidunt. Maecenas a congue urna, sed ullamcorper nibh. Duis at rutrum nisi, quis dignissim justo. Sed mauris ligula, egestas et imperdiet sit amet, dignissim non elit. Etiam sagittis diam quis fringilla pretium. Pellentesque ac lectus velit. Cras euismod felis quis iaculis eleifend. Nullam dapibus neque eu dapibus dignissim. Proin tempor scelerisque massa, et egestas leo pharetra quis. Proin placerat mattis dignissim. Proin maximus urna porta mi convallis, ut pulvinar sem egestas. Duis eget sem vel arcu finibus bibendum nec vitae ligula.

Sed auctor ligula mauris. Aliquam venenatis velit sit amet nulla aliquet pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus est elit, aliquam vel suscipit ut, iaculis in metus. Maecenas placerat vitae elit luctus efficitur. Donec gravida velit at pellentesque pretium. Vivamus ornare pharetra urna a pretium. Vestibulum arcu neque, efficitur volutpat hendrerit quis, consequat sed magna. Sed urna libero, scelerisque a rhoncus in, egestas sed augue. Sed pulvinar ex vel tellus rhoncus, quis commodo dolor luctus. Nunc semper nunc enim, eu pulvinar elit varius vehicula. Nam lobortis, nisl a elementum finibus, ipsum ligula sollicitudin sem, in ultricies nisi metus non quam. Sed cursus, justo ac hendrerit molestie, sapien elit sodales eros, pharetra porta diam neque quis libero. Aliquam dapibus aliquam tempor. Sed consequat nulla at ante imperdiet, condimentum mattis tellus rutrum.

Vestibulum lobortis ac diam sed luctus. Aliquam fringilla fringilla dui, eu tristique purus facilisis a. Nullam laoreet sollicitudin est a laoreet. Donec nec lectus mauris. In hac habitasse platea dictumst. Aliquam semper at nisl et interdum. Fusce vel ipsum justo. Donec consectetur, est eget commodo auctor, mauris dui elementum felis, vel commodo quam nibh ullamcorper eros. Ut commodo vel sem sit amet tempor. Curabitur eget rhoncus lacus. Nullam eget nibh at erat semper commodo. Aliquam erat volutpat.

Nullam vitae tempus ante. Pellentesque sed enim vitae orci condimentum blandit at eu lacus. Maecenas id nibh eget ipsum rutrum consectetur eu a mauris. Nam mattis turpis eget lectus accumsan condimentum. Suspendisse tempor lectus risus, quis porta erat dictum sed. Donec molestie lacinia risus, vitae dictum felis suscipit non. Duis id facilisis leo. Fusce at est mi. Morbi interdum diam in ante vestibulum semper. Vivamus nec consequat eros, id cursus arcu. Donec rhoncus eros nisl, sit amet tincidunt sem sagittis id. Morbi vehicula fermentum ullamcorper. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus magna risus, tincidunt ut ante sit amet, sodales ultricies nisi. Quisque nec cursus lectus.

Nunc turpis nisl, hendrerit vel maximus in, viverra at lorem. Nam finibus tortor arcu, ut mollis tellus porta sit amet. Aliquam erat volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris tincidunt nulla vel consectetur consectetur. Cras non nibh id leo pretium molestie. In sit amet facilisis libero. Maecenas ultricies metus viverra volutpat aliquet. In ac bibendum nisi, vel pharetra mauris. Praesent posuere pellentesque magna, non fringilla enim pellentesque ac. Duis vehicula dapibus pharetra. In maximus ultricies posuere. Suspendisse a pharetra orci.

Ut efficitur ipsum aliquet sem gravida, eu ultricies nisi tincidunt. Pellentesque in nisl eget mauris elementum viverra. Cras ac venenatis risus. Mauris gravida fermentum metus sit amet sollicitudin. Praesent fermentum egestas dapibus. Nam at consequat ante. Duis tempor mi in interdum condimentum. Etiam eu blandit augue, ac luctus nisi. Vestibulum aliquet risus sed quam vehicula, sit amet eleifend velit dapibus. Praesent dapibus aliquam purus at consectetur.

Donec sed vestibulum tellus. Vestibulum ac turpis dui. Sed tincidunt condimentum erat at viverra. Fusce non dictum nunc. Cras pellentesque pellentesque quam a rhoncus. Donec non lacus a eros ornare pretium. Nullam eros magna, varius consectetur fermentum ut, consectetur eget mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur commodo id ante vitae ultrices.

Morbi commodo justo sed ligula auctor, in sodales magna euismod. Sed viverra justo vitae pellentesque molestie. Donec erat velit, commodo eu turpis ut, laoreet placerat leo. Quisque nec efficitur mi. Nunc vehicula sodales facilisis. Aliquam porttitor mauris at eleifend luctus. Pellentesque convallis turpis ut ipsum rutrum, ac lobortis nunc luctus. Donec consectetur pellentesque dapibus. In commodo, lorem ut bibendum consequat, purus mi vestibulum dolor, at elementum dolor dolor vitae sapien. Fusce pretium pretium neque sed finibus. Vivamus blandit vel libero in volutpat. Vivamus vitae pulvinar neque. Suspendisse placerat ante at metus faucibus aliquam. Vestibulum pellentesque metus vitae ipsum aliquet tempor.

Maecenas blandit nulla ac orci porta ullamcorper. Proin vel tincidunt orci. Maecenas cursus accumsan odio, et lacinia lorem convallis eget. Quisque faucibus, arcu ac viverra ultrices, odio ipsum sodales nulla, ut venenatis quam lacus ac lacus. Proin non malesuada urna. Mauris maximus mauris in sapien eleifend, a auctor massa euismod. Quisque vitae ipsum vitae tortor hendrerit convallis. Sed tincidunt consectetur odio eu feugiat. Pellentesque interdum blandit suscipit. Ut quis ante eu ex sagittis condimentum. Duis vel felis nibh. Pellentesque venenatis tristique massa, ac placerat purus venenatis eu. Phasellus consectetur blandit turpis eget ultricies. Morbi semper arcu metus, in placerat dolor aliquam et.

Donec id blandit dolor. Maecenas interdum libero sit amet ante imperdiet, ut sollicitudin nisl pharetra. Morbi egestas massa a cursus dapibus. Aliquam quam urna, fermentum vel tortor id, ullamcorper mollis ligula. Nulla luctus consectetur consequat. Praesent vel turpis id tortor malesuada congue. Sed at ultrices ligula. Nunc congue hendrerit arcu, quis feugiat eros facilisis non. Duis rutrum urna a magna porttitor sollicitudin. Maecenas sed metus fringilla, sodales dolor nec, ornare libero. Proin ac urna quis tellus pharetra imperdiet at eu velit. Ut euismod libero at arcu porta faucibus. In purus nibh, pretium eget pretium vitae, mollis et nisl. Quisque sed ipsum erat. Praesent et tincidunt mi, et luctus velit.

Cras rhoncus pretium lectus, vel scelerisque dolor semper vel. Nulla imperdiet pellentesque scelerisque. Integer ac malesuada enim. Donec a imperdiet nulla, nec venenatis nulla. Duis a tortor mi. Duis dapibus convallis feugiat. Nullam pulvinar pellentesque aliquet. Sed sagittis, lacus eu vulputate dapibus, mauris odio condimentum nunc, sed volutpat mi quam et orci. Pellentesque posuere ex vel nulla facilisis dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer ligula turpis, ullamcorper non rutrum et, mattis at felis. Donec finibus nulla nec sem viverra aliquet. Etiam mattis mi et risus eleifend, non tincidunt justo ultrices. Donec et feugiat ipsum, a gravida neque. Sed vitae tortor ornare, pellentesque sem et, suscipit elit. Curabitur vestibulum venenatis ligula, convallis consequat mauris venenatis vitae.

Phasellus eros risus, feugiat sed risus eu, scelerisque pellentesque tellus. Duis molestie luctus quam, non elementum ligula bibendum a. Suspendisse potenti. Cras egestas velit non semper mollis. Aliquam in eros nunc. Aliquam quis lacinia erat. Ut lacus dolor, maximus id pharetra tincidunt, viverra in lorem. Mauris in tincidunt odio. Nulla nec lacus vel justo iaculis dictum. Suspendisse sed scelerisque justo, id semper leo. Nunc eleifend finibus ex efficitur varius.

Nulla non justo a leo eleifend rhoncus. Morbi pulvinar at leo vitae pharetra. Morbi feugiat, velit in tempus consectetur, magna neque posuere velit, id sollicitudin neque metus a mi. Aliquam nec aliquam nunc. Aliquam suscipit condimentum nulla id vulputate. Proin cursus arcu id lectus auctor, a porta tortor pharetra. Aenean fringilla gravida eros, porta sagittis neque volutpat id. Curabitur id ornare magna, at efficitur nisi. Phasellus non venenatis lorem, eu venenatis dui. Aenean id ex luctus, fringilla leo et, porta ipsum. Pellentesque purus elit, pulvinar at congue in, pretium aliquam metus. Morbi eu purus nisl.

Sed magna leo, lacinia feugiat elementum nec, scelerisque sit amet velit. In molestie scelerisque mauris quis rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc sit amet purus mauris. Etiam vulputate, felis vehicula mollis sollicitudin, justo erat maximus lacus, in feugiat sem ipsum nec urna. Pellentesque dictum justo ut nisl euismod, in iaculis mi sollicitudin. Phasellus gravida eros a nulla euismod viverra. Maecenas ultricies massa sed ultrices feugiat. In ut pretium massa. Donec varius lacus quis faucibus dapibus.

Quisque justo neque, euismod sed mattis sit amet, elementum sit amet tortor. Integer metus leo, mattis eget dapibus tincidunt, placerat vitae est. Ut eu mauris consectetur lacus pulvinar suscipit posuere nec sem. Integer convallis lorem eu dolor aliquet malesuada. Aliquam vel hendrerit purus. Duis non facilisis ante. Nunc turpis sem, hendrerit ac erat in, sagittis ornare dui. Suspendisse et arcu non lacus dapibus lobortis ut a lectus. Suspendisse eu sem mauris. Aliquam a turpis tristique, bibendum dolor vitae, venenatis libero.

Vestibulum volutpat auctor libero. Phasellus viverra faucibus dictum. Quisque at ex non purus lobortis iaculis. Nullam convallis pretium egestas. Aenean lacinia nisl vel elit varius, at venenatis turpis lacinia. Quisque varius dictum erat eu semper. Etiam ante tortor, dignissim sed sagittis at, vestibulum a magna. Mauris eleifend magna eu mauris finibus scelerisque. Vivamus in finibus arcu. Nam blandit velit ex, a efficitur ex consectetur a. Ut id vestibulum augue, sed fringilla felis. Aliquam erat volutpat. Sed rutrum at mauris id facilisis. Maecenas vestibulum justo enim, non dignissim nibh feugiat quis. Fusce sapien elit, fermentum nec bibendum vitae, luctus et mi.

Nam eget lacinia nunc. Nulla tincidunt posuere augue, hendrerit lobortis urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean dictum elementum ante. Duis tristique lectus at ipsum condimentum, quis finibus nulla ornare. Quisque vitae eros maximus, molestie mauris sit amet, lobortis odio. Nunc sollicitudin mi diam, mattis lobortis mi egestas sed. Etiam rutrum risus dignissim magna lacinia, a scelerisque sem egestas.

Aliquam ultricies gravida consequat. In sapien dolor, pretium a aliquet rutrum, rutrum sit amet nisi. Quisque eu sem vel ante bibendum hendrerit ac ac enim. Etiam cursus sed leo ac facilisis. Sed eu tristique nunc. Duis pharetra id urna eu tempus. Praesent varius, mauris sed sollicitudin tempor, mi tellus tempus libero, et blandit turpis lectus eu velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum accumsan ante pretium euismod varius. Fusce aliquam sit amet enim vulputate tempor. Curabitur at placerat eros.

Suspendisse egestas gravida tincidunt. Fusce imperdiet erat laoreet justo auctor tincidunt. Fusce viverra libero non consectetur vestibulum. Quisque tincidunt eu enim eu iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam elit tellus, laoreet ut mollis ac, dictum vitae tortor. Proin ac nisi ac massa pharetra fermentum. Etiam auctor placerat convallis. Ut egestas velit quis dolor lobortis tincidunt. Donec ullamcorper commodo porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim elit, luctus ut magna nec, scelerisque ornare dolor.

Vestibulum feugiat ligula quis nunc gravida sollicitudin quis eget lacus. Duis lorem dolor, tempor quis ornare vel, accumsan quis nulla. Duis aliquam bibendum leo quis commodo. Vivamus eget elit sodales, lacinia nisl eu, pulvinar leo. Suspendisse ac orci commodo magna vulputate euismod. Vestibulum turpis nibh, posuere eget malesuada eu, porttitor in enim. Curabitur non purus nulla.

Fusce id feugiat leo. Nulla ante diam, porttitor quis lorem id, efficitur tempor ipsum. Donec eleifend mauris purus, vel pretium nisl molestie at. Fusce tortor ipsum, finibus lacinia ultrices id, pretium vel ipsum. Quisque finibus nulla a massa varius aliquet. Sed mattis justo at erat elementum, eu rhoncus massa blandit. Pellentesque pretium tincidunt nibh.

Vestibulum nec scelerisque velit, quis hendrerit velit. Maecenas sed posuere massa. Curabitur laoreet bibendum pellentesque. Nam lobortis magna in neque venenatis vulputate. Praesent posuere pharetra finibus. Etiam at efficitur dolor, mattis aliquam lorem. Sed lacus nisl, tincidunt vitae vulputate at, fringilla eget lectus. Fusce et metus sed augue condimentum condimentum a quis felis. Sed nec dolor molestie nisl gravida fringilla et hendrerit mi. Suspendisse eget pulvinar lectus, in tempus lorem.

Etiam sit amet ante quis libero laoreet faucibus eget a enim. Aliquam elementum ligula turpis, eget fringilla tortor hendrerit sed. In faucibus lorem nec nunc faucibus, vitae varius elit tempor. Nam sem ipsum, molestie sed libero in, finibus euismod tellus. Etiam ultrices, eros et posuere eleifend, massa nibh fringilla lorem, id egestas libero libero nec dolor. Nullam eget elit porta, convallis felis facilisis, ultricies nulla. Praesent lobortis felis tincidunt, ullamcorper risus eget, egestas est. Etiam dignissim magna ante, vel ornare sapien vulputate id. Mauris dictum turpis elit, in bibendum ante scelerisque eget. In mauris urna, mollis sed risus a, tincidunt efficitur enim.

Pellentesque vel accumsan leo. Phasellus elementum porttitor commodo. Cras accumsan dignissim mauris, non tincidunt libero tincidunt nec. Fusce ac erat commodo, molestie nisi eu, sodales velit. Nam ut quam a metus gravida posuere eget id lectus. Proin sollicitudin imperdiet maximus. Donec nec erat ultricies, tincidunt nisi euismod, euismod risus. Suspendisse odio ligula, maximus sit amet lacus placerat, commodo egestas lorem. Nullam porta faucibus tellus eu blandit. Integer eu elit massa.

Mauris accumsan augue nulla, ut mollis justo porttitor et. Suspendisse sapien enim, imperdiet vel nibh ac, iaculis dignissim felis. Donec ipsum odio, maximus eu felis et, vehicula placerat est. Quisque pharetra tellus et nisl malesuada, et mattis felis tincidunt. Duis et felis libero. Etiam eu urna aliquet, ultrices quam in, blandit felis. Sed bibendum ex enim, sit amet dictum orci laoreet vel. Nulla posuere mi ipsum. Nam feugiat gravida risus, a sodales turpis varius vitae. Donec a laoreet mauris. Aliquam pulvinar nunc dui, ac sodales justo cursus eu.

Etiam et augue magna. Vivamus tempus, lacus id ullamcorper cursus, sapien lacus egestas erat, eget maximus justo ligula a sapien. Mauris sollicitudin lorem nec turpis facilisis condimentum. Maecenas et fermentum nulla. Aliquam semper, dui sit amet suscipit facilisis, ex dolor ultricies odio, quis consectetur nisl nisl eu nisl. Aliquam sit amet lobortis lectus, ut viverra lorem. Quisque lacinia facilisis ante eu pellentesque. Aliquam erat volutpat. Sed nec sem consectetur, rhoncus massa id, tempor nulla. Vestibulum pellentesque dolor dui, et volutpat sapien efficitur vel. Nulla sit amet ante hendrerit, pharetra lectus eu, efficitur elit. Morbi tincidunt augue ac lacus porta, ut pretium sem sodales. In non iaculis ligula. Integer tincidunt laoreet fermentum.

Aliquam vel vehicula est. In consectetur, nisl quis ornare eleifend, augue lacus sagittis ante, eget pharetra urna turpis nec urna. Praesent orci magna, consequat ac augue a, efficitur aliquam urna. Pellentesque ultricies imperdiet tempus. Sed mollis interdum velit in volutpat. Praesent varius quam non orci eleifend, id euismod ex convallis. Curabitur sit amet libero imperdiet, tristique ante id, blandit massa. Mauris quis massa imperdiet, ullamcorper dui non, laoreet leo. Fusce cursus id ex ut consectetur. Maecenas ac aliquam est, interdum venenatis mauris. Nunc eu risus feugiat, ornare massa vitae, facilisis elit. Fusce quis gravida dui.

Aliquam dapibus lectus ac ligula dignissim aliquam. Mauris ac ipsum sit amet ex dignissim tempor ut et ligula. Sed faucibus magna ex, non malesuada sapien finibus eu. Suspendisse dolor mauris, rutrum vel tempor id, facilisis sed neque. Nam iaculis nec quam in finibus. Etiam ornare porttitor ipsum eu maximus. Curabitur eu magna a enim volutpat lacinia. Praesent vel gravida massa, at pellentesque tellus. Cras semper dignissim ipsum sit amet pulvinar. Curabitur massa nisi, mattis at bibendum nec, fringilla eget nunc. Nunc dictum ipsum vehicula mauris finibus, in pulvinar diam convallis. In nec tempus nisi.

Cras sit amet est dignissim, vulputate massa non, pharetra diam. Curabitur ac scelerisque nunc. Vestibulum ut dui pharetra, tempus sem sit amet, egestas risus. Vestibulum fermentum placerat nisl vel semper. Pellentesque congue ut leo sit amet bibendum. Etiam in tincidunt urna. Quisque augue tellus, luctus eget mi quis, bibendum sodales ante. Curabitur suscipit urna in aliquet vulputate. Sed eget lacus ac est varius faucibus. Phasellus et semper arcu, ut scelerisque ipsum. Quisque luctus eros ac ultrices porta. Nam mattis lorem arcu, in pulvinar nisi cursus sit amet. Vestibulum mauris eros, euismod porttitor ultricies non, fringilla id diam. In pellentesque tempor lectus, non scelerisque ligula interdum sit amet.

Aenean sapien enim, eleifend quis interdum ut, luctus vel risus. Morbi gravida ex a justo sagittis, accumsan aliquet felis venenatis. Morbi nec varius est. Integer commodo imperdiet est. Phasellus sollicitudin viverra felis feugiat luctus. Nam viverra magna vitae nunc placerat semper. Quisque quam elit, fringilla ac tempus vitae, elementum non urna. Cras egestas, augue eu gravida vestibulum, nibh leo scelerisque odio, nec commodo lorem nisi eu ex. Proin ac sem quis ante tristique accumsan.

Fusce vitae nisi sit amet mauris vehicula sagittis. Pellentesque auctor tellus ut volutpat finibus. Nulla facilisi. Fusce gravida leo justo, fermentum sodales ligula tempor ut. Vestibulum tincidunt massa et pulvinar maximus. Vestibulum euismod, odio quis vestibulum varius, elit velit blandit leo, sit amet maximus ante arcu et sem. Sed lacinia consectetur elit. Pellentesque lorem lectus, dapibus vel urna ut, fermentum tristique quam. Sed fringilla fringilla velit, id volutpat elit cursus ut. Nulla ac est dapibus, convallis enim et, dignissim ex.

Donec augue urna, cursus non nunc nec, scelerisque aliquet ipsum. Maecenas non maximus augue, sagittis tincidunt arcu. Aenean condimentum, ligula a blandit vehicula, massa leo dapibus ex, ut blandit magna purus a sem. Sed placerat dapibus vulputate. Maecenas at arcu a tortor viverra mattis quis vel lectus. Integer eget ipsum eget tortor finibus accumsan. Maecenas consectetur turpis diam, sed venenatis sem vehicula id. Curabitur bibendum turpis lacus.
EOS;

$textWithTags = <<<EOS
<comment>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec augue risus. In eu nisl quis augue hendrerit aliquet. Sed tempor metus ac dolor elementum, et volutpat ex vestibulum. Aenean in laoreet mauris. Aenean sagittis libero magna, nec consequat nisi pretium aliquam. Pellentesque egestas est id orci tempus, a vehicula elit cursus. Mauris faucibus commodo quam, quis volutpat diam viverra eget. In hac habitasse platea dictumst. Sed eleifend pellentesque velit, vitae elementum sapien dignissim nec. Nunc rhoncus malesuada odio, vel blandit magna finibus quis. Vestibulum quis mauris lacus. Mauris a malesuada urna.</comment>

Cras sed hendrerit mauris, et condimentum arcu. Vestibulum <error>dictum condimentum ex, sit amet</error> ornare felis placerat et. Nunc dictum convallis massa, vitae efficitur erat varius a. Maecenas venenatis sollicitudin vehicula. Vivamus placerat neque tortor, ullamcorper egestas neque pharetra vel. Quisque molestie malesuada semper. Suspendisse pharetra sem nec dui pharetra vehicula. Proin id pharetra justo, a tempor sapien. Quisque finibus luctus commodo. Nam ligula orci, dictum sit amet auctor sed, tristique nec nisi. Proin faucibus sollicitudin velit, id dictum diam. Donec mollis, nibh sed consequat euismod, ligula elit tempus leo, sed tincidunt mauris tortor consectetur dui. Proin consequat dolor in sagittis posuere. Mauris facilisis felis quam, quis iaculis ligula lacinia vel. Suspendisse a est scelerisque nulla ultrices condimentum quis ut lectus. Etiam id tellus turpis.

Cras augue tellus, molestie sit amet orci id, maximus congue massa. Nam sagittis nisi tortor, vel tempus orci luctus sit amet. Maecenas nunc est, dignissim eu lacus ut, accumsan commodo tortor. Morbi congue malesuada sem, vel faucibus arcu maximus a. Praesent tincidunt ex at ultrices egestas. Nunc nunc tortor, laoreet in eros consequat, hendrerit fringilla mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tincidunt, enim a feugiat vulputate, mi libero convallis velit, ut feugiat risus lectus sit amet ex. Sed porttitor rutrum augue eget vestibulum. Nam ultrices sem vehicula justo pharetra consectetur sed id enim. In tempor pharetra ante id tincidunt.

Aenean tempor <fg=red;bg=white;options=bold>euismod quam, nec venenatis <comment>nulla</comment>. Etiam vitae nisl volutpat, faucibus neque eget, ornare dolor. Ut sapien nisl, vulputate non urna eget, lacinia dictum ante. Pellentesque quis nunc hendrerit, tincidunt dolor vel, lobortis eros. Aenean volutpat ligula velit, varius commodo diam consequat ac. Suspendisse efficitur facilisis condimentum. Maecenas fermentum egestas lacus, in varius dui faucibus et. Proin nec turpis ut quam volutpat auctor id eu libero. Suspendisse potenti. Proin quis velit vel dui dictum mattis. Aliquam erat volutpat. Donec convallis ante a nunc tristique vestibulum. Aliquam at molestie nulla, vel porttitor urna. Duis hendrerit, lacus ut dapibus fermentum, dolor massa gravida nulla</>, sit amet convallis leo mi vel nisl. Curabitur elementum elementum vehicula.

Quisque egestas <info>nunc</info> eget posuere mattis. Fusce eget neque consectetur, sollicitudin ex nec, vulputate felis. Vestibulum purus dolor, pretium vel tempus sed, euismod non dolor. Vivamus ultrices rhoncus risus non scelerisque. Phasellus leo augue, bibendum eget justo vitae, elementum sagittis leo. Curabitur velit magna, congue sit amet mi eu, luctus mattis augue. Morbi vel metus magna. Mauris porta augue dolor, a fringilla mauris interdum vel. In ac suscipit ligula, non ornare mauris. Aenean id venenatis ligula, vel dignissim leo. Donec tortor leo, fringilla in massa sit amet, varius pulvinar nulla. Proin luctus a felis ut dictum.

Duis ut malesuada enim. Sed felis <fg=red;bg=white;options=bold>nisl, porttitor eu lacus eu, ornare vestibulum sapien. Proin pharetra dui quis neque finibus ultricies. Vestibulum id aliquam lacus, id lacinia metus. Duis eget turpis ac neque sollicitudin imperdiet. Maecenas dolor tellus, bibendum ac ligula ac, vehicula consequat ante. Pellentesque turpis elit, tincidunt id semper sit amet, rutrum nec dui. In eget nulla quis sapien pulvinar bibendum eu sit amet nunc. Aliquam vel ullamcorper dui. Cras nec dolor sit amet dolor euismod aliquet</>.

Morbi <comment>id <info>mauris <error>turpis</error>. Etiam faucibus</info> euismod neque nec pretium. Duis vitae nisi volutpat, porttitor est a, condimentum metus. Nam viverra iaculis ligula sit amet blandit. Morbi quis sem tristique, convallis justo in, ultrices nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque condimentum cursus molestie. Maecenas condimentum dapibus velit sit amet pretium. Integer a arcu et diam pretium dignissim nec id tellus. Ut nec elementum nibh, sit amet finibus ligula.</comment>

Class <fg=red;bg=white;options=bold>aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean leo augue, tempor nec finibus pharetra, tincidunt id libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pellentesque vitae dolor a rutrum. Sed congue consectetur sapien. Vivamus quis varius orci. Proin eget consequat dolor. Proin eu sagittis ex, quis porta est. Proin varius iaculis justo. Aliquam et lacus et nulla sollicitudin laoreet in at sem. Sed velit est, lacinia id risus sit amet, convallis finibus ante. Quisque ut turpis quis nunc facilisis sodales. Aenean viverra tortor sed feugiat tristique. Sed lectus arcu</>, imperdiet quis sodales sed, lobortis id ligula. Praesent aliquet eleifend placerat. Ut in magna pulvinar, rutrum sem vehicula, interdum leo.

\<comment>Phasellus id ipsum quis\</comment> sem lobortis ullamcorper. Quisque laoreet erat turpis, ut <info>aliquam magna ornare id. Nullam id leo eu mi suscipit tincidunt</info>. In consectetur ac sapien vitae facilisis. Aenean viverra nibh in purus mattis, sed tincidunt purus lobortis. Mauris eget erat mattis, rhoncus neque et, tincidunt lacus. Donec sed luctus purus.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam efficitur vitae felis eget molestie. Donec erat odio, rutrum id ornare vel, accumsan vel tellus. Suspendisse eros velit, ornare blandit turpis at, imperdiet sollicitudin dui. Maecenas interdum, est a scelerisque semper, diam augue fermentum mi, at tincidunt odio leo in nibh. Nulla interdum eros ac euismod egestas. Nam in magna dapibus, ultricies nibh at, sagittis leo. Vestibulum nec egestas velit.

Nullam eleifend leo sapien, <fg=red;bg=white;options=bold>vel aliquet dolor rutrum ut. Maecenas</> consectetur <fg=red;bg=white;options=bold>elit nec massa placerat</>, in cursus mi varius. Sed sed ante ut nisl tincidunt elementum. Sed dictum nisl eget nibh imperdiet cursus. Praesent posuere convallis convallis. Nulla nec massa quis diam dictum convallis. Morbi non diam nisi. Pellentesque elit nisl, tincidunt in mi ac, mollis vehicula risus. In cursus ligula ut dolor mollis congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus at enim sed felis fringilla efficitur.

Praesent lacus magna, <error>rutrum malesuada dapibus in, gravida a risus</error>. <b>Suspendisse</b> euismod diam velit, at condimentum magna volutpat nec. Duis tempor ut sem a egestas. Etiam volutpat sem ultricies congue pharetra. Maecenas vitae nisi et lectus pulvinar lacinia ac a velit. Integer at mi eget leo dignissim porta. Phasellus luctus enim vel sem interdum consectetur. Nunc interdum, magna nec commodo tempor, diam ex sollicitudin mi, vitae tempus tortor sem id purus. Pellentesque semper mattis eros, et sollicitudin orci pellentesque sed. Nunc aliquet leo sit amet varius iaculis. Phasellus eget libero convallis, lobortis ligula in, rutrum lectus. Aliquam erat volutpat. Cras in tristique enim.

Vivamus fermentum vestibulum <fg=red;bg=white;options=bold,underscore>tempor</>. Maecenas mollis id risus at rutrum. <error>Quisque sodales eget</error> metus <info>blandit viverra</info>. In quis consectetur orci. Proin viverra placerat consequat. Aenean arcu justo, ultrices nec semper id, feugiat a orci. <info>Aenean posuere nisl malesuada magna sollicitudin, ultricies luctus eros vehicula. Vestibulum bibendum et purus fringilla vulputate.</info>

<comment>Suspendisse</comment> <info>sollicitudin</info> <error>molestie</error> <fg=red;bg=white;options=bold>congue</>. Etiam tristique suscipit risus, vel tristique mauris cursus vitae. Phasellus semper urna quis orci ultrices finibus. Aliquam convallis risus placerat nisi laoreet, eu scelerisque enim maximus. Duis eleifend in augue quis laoreet. Ut ligula justo, fermentum id dolor vitae, facilisis congue augue. Nunc ac ultricies dui, quis pharetra purus. Nullam auctor consequat mollis. In velit velit, tincidunt id mi ut, molestie accumsan erat.

Donec luctus sem vel sapien dignissim ultricies. Etiam quis enim nulla. Curabitur consequat elit in dui placerat, sed euismod sem mattis. Fusce ultricies posuere tellus, a facilisis elit rutrum bibendum. Donec consequat feugiat orci ac blandit. Quisque ac neque nisi. Pellentesque placerat volutpat mauris, et accumsan ex dignissim at. Cras sagittis, mi nec malesuada dignissim, lectus enim ultricies justo, vitae venenatis felis velit in quam. Suspendisse potenti.

Donec elementum, risus in auctor euismod, purus sapien pellentesque lacus, ut sollicitudin erat purus quis urna. Maecenas non massa tincidunt, ullamcorper turpis vitae, egestas nulla. Fusce sit amet risus pharetra, efficitur augue ac, dictum elit. Sed eget sapien erat. Ut tempus bibendum varius. In elementum, ipsum et viverra malesuada, ligula ex convallis eros, ac facilisis arcu lectus eu justo. Curabitur venenatis consequat massa, ut dictum nisl posuere vitae.

Aenean pellentesque velit non molestie auctor. Vestibulum ut velit turpis. Sed vitae nisl maximus leo vestibulum bibendum eu sed arcu. Suspendisse mollis nibh non tellus pretium, eu accumsan mauris aliquam. Suspendisse vitae magna finibus, dictum orci at, eleifend purus. Mauris viverra sollicitudin quam id tincidunt. Quisque condimentum ac mi vel aliquam.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis sodales tortor urna, et volutpat magna aliquet in. Proin aliquet iaculis dolor, ac lacinia purus faucibus eu. Curabitur at tincidunt sapien. Donec ullamcorper hendrerit neque, in condimentum velit suscipit a. Donec viverra dui sit amet leo sodales, vel rutrum nunc elementum. Mauris eget massa molestie, placerat leo in, varius lectus.

In a mi eu ex finibus dictum. Sed viverra consectetur velit. Curabitur consectetur tortor nec egestas tincidunt. Maecenas a congue urna, sed ullamcorper nibh. Duis at rutrum nisi, quis dignissim justo. Sed mauris ligula, egestas et imperdiet sit amet, dignissim non elit. Etiam sagittis diam quis fringilla pretium. Pellentesque ac lectus velit. Cras euismod felis quis iaculis eleifend. Nullam dapibus neque eu dapibus dignissim. Proin tempor scelerisque massa, et egestas leo pharetra quis. Proin placerat mattis dignissim. Proin maximus urna porta mi convallis, ut pulvinar sem egestas. Duis eget sem vel arcu finibus bibendum nec vitae ligula.

Sed auctor ligula mauris. Aliquam venenatis velit sit amet nulla aliquet pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus est elit, aliquam vel suscipit ut, iaculis in metus. Maecenas placerat vitae elit luctus efficitur. Donec gravida velit at pellentesque pretium. Vivamus ornare pharetra urna a pretium. Vestibulum arcu neque, efficitur volutpat hendrerit quis, consequat sed magna. Sed urna libero, scelerisque a rhoncus in, egestas sed augue. Sed pulvinar ex vel tellus rhoncus, quis commodo dolor luctus. Nunc semper nunc enim, eu pulvinar elit varius vehicula. Nam lobortis, nisl a elementum finibus, ipsum ligula sollicitudin sem, in ultricies nisi metus non quam. Sed cursus, justo ac hendrerit molestie, sapien elit sodales eros, pharetra porta diam neque quis libero. Aliquam dapibus aliquam tempor. Sed consequat nulla at ante imperdiet, condimentum mattis tellus rutrum.

Vestibulum lobortis ac diam sed luctus. Aliquam fringilla fringilla dui, eu tristique purus facilisis a. Nullam laoreet sollicitudin est a laoreet. Donec nec lectus mauris. In hac habitasse platea dictumst. Aliquam semper at nisl et interdum. Fusce vel ipsum justo. Donec consectetur, est eget commodo auctor, mauris dui elementum felis, vel commodo quam nibh ullamcorper eros. Ut commodo vel sem sit amet tempor. Curabitur eget rhoncus lacus. Nullam eget nibh at erat semper commodo. Aliquam erat volutpat.

Nullam vitae tempus ante. Pellentesque sed enim vitae orci condimentum blandit at eu lacus. Maecenas id nibh eget ipsum rutrum consectetur eu a mauris. Nam mattis turpis eget lectus accumsan condimentum. Suspendisse tempor lectus risus, quis porta erat dictum sed. Donec molestie lacinia risus, vitae dictum felis suscipit non. Duis id facilisis leo. Fusce at est mi. Morbi interdum diam in ante vestibulum semper. Vivamus nec consequat eros, id cursus arcu. Donec rhoncus eros nisl, sit amet tincidunt sem sagittis id. Morbi vehicula fermentum ullamcorper. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus magna risus, tincidunt ut ante sit amet, sodales ultricies nisi. Quisque nec cursus lectus.

Nunc turpis nisl, hendrerit vel maximus in, viverra at lorem. Nam finibus tortor arcu, ut mollis tellus porta sit amet. Aliquam erat volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris tincidunt nulla vel consectetur consectetur. Cras non nibh id leo pretium molestie. In sit amet facilisis libero. Maecenas ultricies metus viverra volutpat aliquet. In ac bibendum nisi, vel pharetra mauris. Praesent posuere pellentesque magna, non fringilla enim pellentesque ac. Duis vehicula dapibus pharetra. In maximus ultricies posuere. Suspendisse a pharetra orci.

Ut efficitur ipsum aliquet sem gravida, eu ultricies nisi tincidunt. Pellentesque in nisl eget mauris elementum viverra. Cras ac venenatis risus. Mauris gravida fermentum metus sit amet sollicitudin. Praesent fermentum egestas dapibus. Nam at consequat ante. Duis tempor mi in interdum condimentum. Etiam eu blandit augue, ac luctus nisi. Vestibulum aliquet risus sed quam vehicula, sit amet eleifend velit dapibus. Praesent dapibus aliquam purus at consectetur.

Donec sed vestibulum tellus. Vestibulum ac turpis dui. Sed tincidunt condimentum erat at viverra. Fusce non dictum nunc. Cras pellentesque pellentesque quam a rhoncus. Donec non lacus a eros ornare pretium. Nullam eros magna, varius consectetur fermentum ut, consectetur eget mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur commodo id ante vitae ultrices.

Morbi commodo justo sed ligula auctor, in sodales magna euismod. Sed viverra justo vitae pellentesque molestie. Donec erat velit, commodo eu turpis ut, laoreet placerat leo. Quisque nec efficitur mi. Nunc vehicula sodales facilisis. Aliquam porttitor mauris at eleifend luctus. Pellentesque convallis turpis ut ipsum rutrum, ac lobortis nunc luctus. Donec consectetur pellentesque dapibus. In commodo, lorem ut bibendum consequat, purus mi vestibulum dolor, at elementum dolor dolor vitae sapien. Fusce pretium pretium neque sed finibus. Vivamus blandit vel libero in volutpat. Vivamus vitae pulvinar neque. Suspendisse placerat ante at metus faucibus aliquam. Vestibulum pellentesque metus vitae ipsum aliquet tempor.

Maecenas blandit nulla ac orci porta ullamcorper. Proin vel tincidunt orci. Maecenas cursus accumsan odio, et lacinia lorem convallis eget. Quisque faucibus, arcu ac viverra ultrices, odio ipsum sodales nulla, ut venenatis quam lacus ac lacus. Proin non malesuada urna. Mauris maximus mauris in sapien eleifend, a auctor massa euismod. Quisque vitae ipsum vitae tortor hendrerit convallis. Sed tincidunt consectetur odio eu feugiat. Pellentesque interdum blandit suscipit. Ut quis ante eu ex sagittis condimentum. Duis vel felis nibh. Pellentesque venenatis tristique massa, ac placerat purus venenatis eu. Phasellus consectetur blandit turpis eget ultricies. Morbi semper arcu metus, in placerat dolor aliquam et.

Donec id blandit dolor. Maecenas interdum libero sit amet ante imperdiet, ut sollicitudin nisl pharetra. Morbi egestas massa a cursus dapibus. Aliquam quam urna, fermentum vel tortor id, ullamcorper mollis ligula. Nulla luctus consectetur consequat. Praesent vel turpis id tortor malesuada congue. Sed at ultrices ligula. Nunc congue hendrerit arcu, quis feugiat eros facilisis non. Duis rutrum urna a magna porttitor sollicitudin. Maecenas sed metus fringilla, sodales dolor nec, ornare libero. Proin ac urna quis tellus pharetra imperdiet at eu velit. Ut euismod libero at arcu porta faucibus. In purus nibh, pretium eget pretium vitae, mollis et nisl. Quisque sed ipsum erat. Praesent et tincidunt mi, et luctus velit.

Cras rhoncus pretium lectus, vel scelerisque dolor semper vel. Nulla imperdiet pellentesque scelerisque. Integer ac malesuada enim. Donec a imperdiet nulla, nec venenatis nulla. Duis a tortor mi. Duis dapibus convallis feugiat. Nullam pulvinar pellentesque aliquet. Sed sagittis, lacus eu vulputate dapibus, mauris odio condimentum nunc, sed volutpat mi quam et orci. Pellentesque posuere ex vel nulla facilisis dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer ligula turpis, ullamcorper non rutrum et, mattis at felis. Donec finibus nulla nec sem viverra aliquet. Etiam mattis mi et risus eleifend, non tincidunt justo ultrices. Donec et feugiat ipsum, a gravida neque. Sed vitae tortor ornare, pellentesque sem et, suscipit elit. Curabitur vestibulum venenatis ligula, convallis consequat mauris venenatis vitae.

Phasellus eros risus, feugiat sed risus eu, scelerisque pellentesque tellus. Duis molestie luctus quam, non elementum ligula bibendum a. Suspendisse potenti. Cras egestas velit non semper mollis. Aliquam in eros nunc. Aliquam quis lacinia erat. Ut lacus dolor, maximus id pharetra tincidunt, viverra in lorem. Mauris in tincidunt odio. Nulla nec lacus vel justo iaculis dictum. Suspendisse sed scelerisque justo, id semper leo. Nunc eleifend finibus ex efficitur varius.

Nulla non justo a leo eleifend rhoncus. Morbi pulvinar at leo vitae pharetra. Morbi feugiat, velit in tempus consectetur, magna neque posuere velit, id sollicitudin neque metus a mi. Aliquam nec aliquam nunc. Aliquam suscipit condimentum nulla id vulputate. Proin cursus arcu id lectus auctor, a porta tortor pharetra. Aenean fringilla gravida eros, porta sagittis neque volutpat id. Curabitur id ornare magna, at efficitur nisi. Phasellus non venenatis lorem, eu venenatis dui. Aenean id ex luctus, fringilla leo et, porta ipsum. Pellentesque purus elit, pulvinar at congue in, pretium aliquam metus. Morbi eu purus nisl.

Sed magna leo, lacinia feugiat elementum nec, scelerisque sit amet velit. In molestie scelerisque mauris quis rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc sit amet purus mauris. Etiam vulputate, felis vehicula mollis sollicitudin, justo erat maximus lacus, in feugiat sem ipsum nec urna. Pellentesque dictum justo ut nisl euismod, in iaculis mi sollicitudin. Phasellus gravida eros a nulla euismod viverra. Maecenas ultricies massa sed ultrices feugiat. In ut pretium massa. Donec varius lacus quis faucibus dapibus.

Quisque justo neque, euismod sed mattis sit amet, elementum sit amet tortor. Integer metus leo, mattis eget dapibus tincidunt, placerat vitae est. Ut eu mauris consectetur lacus pulvinar suscipit posuere nec sem. Integer convallis lorem eu dolor aliquet malesuada. Aliquam vel hendrerit purus. Duis non facilisis ante. Nunc turpis sem, hendrerit ac erat in, sagittis ornare dui. Suspendisse et arcu non lacus dapibus lobortis ut a lectus. Suspendisse eu sem mauris. Aliquam a turpis tristique, bibendum dolor vitae, venenatis libero.

Vestibulum volutpat auctor libero. Phasellus viverra faucibus dictum. Quisque at ex non purus lobortis iaculis. Nullam convallis pretium egestas. Aenean lacinia nisl vel elit varius, at venenatis turpis lacinia. Quisque varius dictum erat eu semper. Etiam ante tortor, dignissim sed sagittis at, vestibulum a magna. Mauris eleifend magna eu mauris finibus scelerisque. Vivamus in finibus arcu. Nam blandit velit ex, a efficitur ex consectetur a. Ut id vestibulum augue, sed fringilla felis. Aliquam erat volutpat. Sed rutrum at mauris id facilisis. Maecenas vestibulum justo enim, non dignissim nibh feugiat quis. Fusce sapien elit, fermentum nec bibendum vitae, luctus et mi.

Nam eget lacinia nunc. Nulla tincidunt posuere augue, hendrerit lobortis urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean dictum elementum ante. Duis tristique lectus at ipsum condimentum, quis finibus nulla ornare. Quisque vitae eros maximus, molestie mauris sit amet, lobortis odio. Nunc sollicitudin mi diam, mattis lobortis mi egestas sed. Etiam rutrum risus dignissim magna lacinia, a scelerisque sem egestas.

Aliquam ultricies gravida consequat. In sapien dolor, pretium a aliquet rutrum, rutrum sit amet nisi. Quisque eu sem vel ante bibendum hendrerit ac ac enim. Etiam cursus sed leo ac facilisis. Sed eu tristique nunc. Duis pharetra id urna eu tempus. Praesent varius, mauris sed sollicitudin tempor, mi tellus tempus libero, et blandit turpis lectus eu velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum accumsan ante pretium euismod varius. Fusce aliquam sit amet enim vulputate tempor. Curabitur at placerat eros.

Suspendisse egestas gravida tincidunt. Fusce imperdiet erat laoreet justo auctor tincidunt. Fusce viverra libero non consectetur vestibulum. Quisque tincidunt eu enim eu iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam elit tellus, laoreet ut mollis ac, dictum vitae tortor. Proin ac nisi ac massa pharetra fermentum. Etiam auctor placerat convallis. Ut egestas velit quis dolor lobortis tincidunt. Donec ullamcorper commodo porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim elit, luctus ut magna nec, scelerisque ornare dolor.

Vestibulum feugiat ligula quis nunc gravida sollicitudin quis eget lacus. Duis lorem dolor, tempor quis ornare vel, accumsan quis nulla. Duis aliquam bibendum leo quis commodo. Vivamus eget elit sodales, lacinia nisl eu, pulvinar leo. Suspendisse ac orci commodo magna vulputate euismod. Vestibulum turpis nibh, posuere eget malesuada eu, porttitor in enim. Curabitur non purus nulla.

Fusce id feugiat leo. Nulla ante diam, porttitor quis lorem id, efficitur tempor ipsum. Donec eleifend mauris purus, vel pretium nisl molestie at. Fusce tortor ipsum, finibus lacinia ultrices id, pretium vel ipsum. Quisque finibus nulla a massa varius aliquet. Sed mattis justo at erat elementum, eu rhoncus massa blandit. Pellentesque pretium tincidunt nibh.

Vestibulum nec scelerisque velit, quis hendrerit velit. Maecenas sed posuere massa. Curabitur laoreet bibendum pellentesque. Nam lobortis magna in neque venenatis vulputate. Praesent posuere pharetra finibus. Etiam at efficitur dolor, mattis aliquam lorem. Sed lacus nisl, tincidunt vitae vulputate at, fringilla eget lectus. Fusce et metus sed augue condimentum condimentum a quis felis. Sed nec dolor molestie nisl gravida fringilla et hendrerit mi. Suspendisse eget pulvinar lectus, in tempus lorem.

Etiam sit amet ante quis libero laoreet faucibus eget a enim. Aliquam elementum ligula turpis, eget fringilla tortor hendrerit sed. In faucibus lorem nec nunc faucibus, vitae varius elit tempor. Nam sem ipsum, molestie sed libero in, finibus euismod tellus. Etiam ultrices, eros et posuere eleifend, massa nibh fringilla lorem, id egestas libero libero nec dolor. Nullam eget elit porta, convallis felis facilisis, ultricies nulla. Praesent lobortis felis tincidunt, ullamcorper risus eget, egestas est. Etiam dignissim magna ante, vel ornare sapien vulputate id. Mauris dictum turpis elit, in bibendum ante scelerisque eget. In mauris urna, mollis sed risus a, tincidunt efficitur enim.

Pellentesque vel accumsan leo. Phasellus elementum porttitor commodo. Cras accumsan dignissim mauris, non tincidunt libero tincidunt nec. Fusce ac erat commodo, molestie nisi eu, sodales velit. Nam ut quam a metus gravida posuere eget id lectus. Proin sollicitudin imperdiet maximus. Donec nec erat ultricies, tincidunt nisi euismod, euismod risus. Suspendisse odio ligula, maximus sit amet lacus placerat, commodo egestas lorem. Nullam porta faucibus tellus eu blandit. Integer eu elit massa.

Mauris accumsan augue nulla, ut mollis justo porttitor et. Suspendisse sapien enim, imperdiet vel nibh ac, iaculis dignissim felis. Donec ipsum odio, maximus eu felis et, vehicula placerat est. Quisque pharetra tellus et nisl malesuada, et mattis felis tincidunt. Duis et felis libero. Etiam eu urna aliquet, ultrices quam in, blandit felis. Sed bibendum ex enim, sit amet dictum orci laoreet vel. Nulla posuere mi ipsum. Nam feugiat gravida risus, a sodales turpis varius vitae. Donec a laoreet mauris. Aliquam pulvinar nunc dui, ac sodales justo cursus eu.

Etiam et augue magna. Vivamus tempus, lacus id ullamcorper cursus, sapien lacus egestas erat, eget maximus justo ligula a sapien. Mauris sollicitudin lorem nec turpis facilisis condimentum. Maecenas et fermentum nulla. Aliquam semper, dui sit amet suscipit facilisis, ex dolor ultricies odio, quis consectetur nisl nisl eu nisl. Aliquam sit amet lobortis lectus, ut viverra lorem. Quisque lacinia facilisis ante eu pellentesque. Aliquam erat volutpat. Sed nec sem consectetur, rhoncus massa id, tempor nulla. Vestibulum pellentesque dolor dui, et volutpat sapien efficitur vel. Nulla sit amet ante hendrerit, pharetra lectus eu, efficitur elit. Morbi tincidunt augue ac lacus porta, ut pretium sem sodales. In non iaculis ligula. Integer tincidunt laoreet fermentum.

Aliquam vel vehicula est. In consectetur, nisl quis ornare eleifend, augue lacus sagittis ante, eget pharetra urna turpis nec urna. Praesent orci magna, consequat ac augue a, efficitur aliquam urna. Pellentesque ultricies imperdiet tempus. Sed mollis interdum velit in volutpat. Praesent varius quam non orci eleifend, id euismod ex convallis. Curabitur sit amet libero imperdiet, tristique ante id, blandit massa. Mauris quis massa imperdiet, ullamcorper dui non, laoreet leo. Fusce cursus id ex ut consectetur. Maecenas ac aliquam est, interdum venenatis mauris. Nunc eu risus feugiat, ornare massa vitae, facilisis elit. Fusce quis gravida dui.

Aliquam dapibus lectus ac ligula dignissim aliquam. Mauris ac ipsum sit amet ex dignissim tempor ut et ligula. Sed faucibus magna ex, non malesuada sapien finibus eu. Suspendisse dolor mauris, rutrum vel tempor id, facilisis sed neque. Nam iaculis nec quam in finibus. Etiam ornare porttitor ipsum eu maximus. Curabitur eu magna a enim volutpat lacinia. Praesent vel gravida massa, at pellentesque tellus. Cras semper dignissim ipsum sit amet pulvinar. Curabitur massa nisi, mattis at bibendum nec, fringilla eget nunc. Nunc dictum ipsum vehicula mauris finibus, in pulvinar diam convallis. In nec tempus nisi.

Cras sit amet est dignissim, vulputate massa non, pharetra diam. Curabitur ac scelerisque nunc. Vestibulum ut dui pharetra, tempus sem sit amet, egestas risus. Vestibulum fermentum placerat nisl vel semper. Pellentesque congue ut leo sit amet bibendum. Etiam in tincidunt urna. Quisque augue tellus, luctus eget mi quis, bibendum sodales ante. Curabitur suscipit urna in aliquet vulputate. Sed eget lacus ac est varius faucibus. Phasellus et semper arcu, ut scelerisque ipsum. Quisque luctus eros ac ultrices porta. Nam mattis lorem arcu, in pulvinar nisi cursus sit amet. Vestibulum mauris eros, euismod porttitor ultricies non, fringilla id diam. In pellentesque tempor lectus, non scelerisque ligula interdum sit amet.

Aenean sapien enim, eleifend quis interdum ut, luctus vel risus. Morbi gravida ex a justo sagittis, accumsan aliquet felis venenatis. Morbi nec varius est. Integer commodo imperdiet est. Phasellus sollicitudin viverra felis feugiat luctus. Nam viverra magna vitae nunc placerat semper. Quisque quam elit, fringilla ac tempus vitae, elementum non urna. Cras egestas, augue eu gravida vestibulum, nibh leo scelerisque odio, nec commodo lorem nisi eu ex. Proin ac sem quis ante tristique accumsan.

Fusce vitae nisi sit amet mauris vehicula sagittis. Pellentesque auctor tellus ut volutpat finibus. Nulla facilisi. Fusce gravida leo justo, fermentum sodales ligula tempor ut. Vestibulum tincidunt massa et pulvinar maximus. Vestibulum euismod, odio quis vestibulum varius, elit velit blandit leo, sit amet maximus ante arcu et sem. Sed lacinia consectetur elit. Pellentesque lorem lectus, dapibus vel urna ut, fermentum tristique quam. Sed fringilla fringilla velit, id volutpat elit cursus ut. Nulla ac est dapibus, convallis enim et, dignissim ex.

Donec augue urna, cursus non nunc nec, scelerisque aliquet ipsum. Maecenas non maximus augue, sagittis tincidunt arcu. Aenean condimentum, ligula a blandit vehicula, massa leo dapibus ex, ut blandit magna purus a sem. Sed placerat dapibus vulputate. Maecenas at arcu a tortor viverra mattis quis vel lectus. Integer eget ipsum eget tortor finibus accumsan. Maecenas consectetur turpis diam, sed venenatis sem vehicula id. Curabitur bibendum turpis lacus.
EOS;

$outputFormatter = new \Symfony\Component\Console\Formatter\TokenizeOutputFormatter(true);
$loop = 100;

$times = [];
$start = microtime(true);
for ($i=0;$i<$loop;$i++) {
    $outputFormatter->format($textShort);
}
$end = microtime(true);
$times['Short'] = $end - $start;

$start = microtime(true);
for ($i=0;$i<$loop;$i++) {
    $outputFormatter->format($textShortWithTags);
}
$end = microtime(true);
$times['Short with tags'] = $end - $start;

$start = microtime(true);
for ($i=0;$i<$loop;$i++) {
    $outputFormatter->format($textSimple);
}
$end = microtime(true);
$times['Simple'] = $end - $start;

$start = microtime(true);
for ($i=0;$i<$loop;$i++) {
    $outputFormatter->format($textWithTags);
}
$end = microtime(true);
$times['With tags'] = $end - $start;

foreach ($times as $title => $time) {
    printf("%-15s %01.2fs\n", $title, $time);
}
